default:
  image: ubuntu:24.04

stages:
  - build

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - >
      apt-get -y install python3-pip ninja-build libglib2.0-dev
      libxml2-utils zip gettext
    - pip3 install --break-system-packages meson==1.4.0
    - apt-get -y install nodejs npm
    - npm install -g eslint@8.57.0 eslint-plugin-jsdoc@48.2.3
  script:
    - meson _build -Dbuild_zip=true
    - meson test -C _build
    - meson install -C _build
  artifacts:
    name: '$CI_JOB_NAME'
    paths:
      - _build
    expire_in: 1 day
