project_identifier: docket
commit_message: New translations (%language%)
append_commit_message:
files:
  - source: /data/po/org.gnome.shell.extensions.docket.pot
    translation: /data/po/%locale%.po
    languages_mapping:
      locale:
        de: de
        fr: fr
        lt: lt
        nl: nl
        uk: uk
        ru: ru
        it: it
        sv-SE: sv
        pt-BR: pt_BR
